development:
  adapter: postgresql
  database: trellino_development
  host: localhost
  username: phil
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: trellino_development
  host: localhost
  username: phil
  pool: 5
  timeout: 5000

# production:
#   adapter: postgresql
#   database: trellino_development
#   host: localhost
#   username: phil
#   pool: 5
#   timeout: 5000