development:
  adapter: sqlite3
  database: db/trellino_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/trellino_test
  host: localhost
  pool: 5
  timeout: 5000
